'use client';
import {useEffect,useRef,useState} from 'react';
import gsap from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import Lenis from 'lenis';
import TrafficScene from './TrafficScene';
import ScrollMetric from './ScrollMetric';
import TemakExperience from './TemakExperience';
const whatsappUrl='https://wa.me/message/TGECUVN3HZRYO1';
const services=[{n:'01',title:'Planejamento de mídia',desc:'O objetivo do negócio orienta a campanha.',items:'Diagnóstico · Público · Oferta · Investimento'},{n:'02',title:'Meta Ads & Google Ads',desc:'Anúncios com direção, do criativo à busca.',items:'Campanhas · Criativos · Segmentação · Remarketing'},{n:'03',title:'Caminho para converter',desc:'O clique precisa encontrar um próximo passo.',items:'Sites · Landing pages · WhatsApp · CRM'},{n:'04',title:'Gestão e otimização',desc:'Acompanhar, aprender e melhorar continuamente.',items:'Análise de dados · Testes · Ajustes · Acompanhamento'}];
const cases=[{tag:'DELIVERY',value:'+ R$ 500 mil',unit:'em vendas de delivery',title:'Anúncios que abrem o apetite. E geram pedidos.',desc:'Mais de R$ 500 mil em vendas de delivery ao longo dos trabalhos realizados pela Rise.',stats:[['+ R$ 500 mil','Vendas acumuladas'],['Delivery','Frente de atuação']],note:'Valor acumulado informado pela Rise, sem período definido neste material. Não representa lucro.'},{tag:'E-COMMERCE',value:'+ R$ 1 milhão',unit:'em vendas de orquídeas pelo site',title:'Da descoberta à compra de uma orquídea.',desc:'Mais de R$ 1 milhão em vendas de orquídeas em site próprio. Experiência de tráfego pago aplicada ao e-commerce.',stats:[['+ R$ 1 milhão','Vendas acumuladas'],['Site próprio','Canal de venda']],note:'Vendas em site, não em marketplace. Valor acumulado informado pela Rise; não representa lucro.'},{tag:'GERAÇÃO DE LEADS',value:'+ 50 mil',unit:'leads para diferentes negócios',title:'Oportunidades para negócios de verdade.',desc:'Mais de 50 mil leads gerados para diferentes negócios. Experiência atendendo clínicas, restaurantes, escolas e outros segmentos.',stats:[['+ 50 mil','Leads gerados'],['Vários setores','Experiência de atuação']],note:'Volume acumulado informado pela Rise. Leads são contatos gerados, não vendas confirmadas.'}];
export default function Home(){const root=useRef<HTMLElement>(null);const [selected,setSelected]=useState(0);
useEffect(()=>{gsap.registerPlugin(ScrollTrigger);const mm=gsap.matchMedia();let lenis:Lenis|undefined;let tick:((t:number)=>void)|undefined;mm.add('(prefers-reduced-motion: no-preference)',()=>{lenis=new Lenis({duration:1.05,anchors:true});lenis.on('scroll',ScrollTrigger.update);tick=t=>lenis?.raf(t*1000);gsap.ticker.add(tick);const ctx=gsap.context(()=>{gsap.from('.hero h1',{y:35,opacity:0,duration:1,ease:'power3.out'});gsap.fromTo('.hero-curve',{strokeDasharray:1,strokeDashoffset:1},{strokeDashoffset:0,duration:1.8,ease:'power2.out'});gsap.utils.toArray<HTMLElement>('.reveal').forEach(el=>gsap.from(el,{y:36,opacity:0,duration:.8,ease:'power2.out',scrollTrigger:{trigger:el,start:'top 88%',once:true}}));gsap.to('.manifesto .muted',{opacity:.22,scrollTrigger:{trigger:'.manifesto',start:'top 55%',end:'bottom 60%',scrub:true}});gsap.fromTo('.manifesto strong',{color:'#515645'},{color:'#c4f45b',scrollTrigger:{trigger:'.manifesto',start:'top 45%',end:'bottom 65%',scrub:true}});},root);return()=>{ctx.revert();if(tick)gsap.ticker.remove(tick);lenis?.destroy()}});return()=>mm.revert()},[]);
const c=cases[selected];
return <main ref={root}><a className="skip" href="#conteudo">Pular para o conteúdo</a><header><a className="logo brand-logo" href="#" aria-label="Rise Agency, início"><img src="/rise-logo-transparent.png" alt="Rise Agency"/></a><nav aria-label="Navegação principal"><a href="#resultados">Resultados</a><a href="#trafego">Tráfego pago</a><a href="#metodo">Nosso método</a><a className="button small" href={whatsappUrl} target="_blank" rel="noopener noreferrer">Vamos conversar</a></nav></header>
<section className="hero" id="conteudo"><div className="eyebrow">META ADS + GOOGLE ADS / GESTÃO DE TRÁFEGO</div><h1>Seu negócio.<br/>Na frente de quem<br/><em>quer comprar.</em></h1><div className="hero-bottom"><p>Tráfego pago com estratégia, gestão próxima e foco em vendas.<br className="desktop"/> Do anúncio à conversão, a Rise acompanha o caminho.</p><a className="button" href={whatsappUrl} target="_blank" rel="noopener noreferrer">Agendar uma reunião</a></div><div className="hero-report" aria-hidden="true"><div className="hero-report-top"><span>RISE / PERFORMANCE</span><span>DEMONSTRAÇÃO</span></div><div className="hero-report-title">O crescimento<br/>tem um caminho.</div><svg viewBox="0 0 360 180"><defs><linearGradient id="hero-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#b6ff00" stopOpacity=".25"/><stop offset="100%" stopColor="#b6ff00" stopOpacity="0"/></linearGradient></defs>{[40,90,140].map(y=><line key={y} x1="0" y1={y} x2="360" y2={y} stroke="#2d5030" strokeDasharray="3 6"/>)}<path d="M0 145 L35 131 L70 137 L105 102 L140 111 L180 77 L220 91 L260 49 L305 58 L355 15 L355 180 L0 180 Z" fill="url(#hero-fill)"/><path className="hero-curve" d="M0 145 L35 131 L70 137 L105 102 L140 111 L180 77 L220 91 L260 49 L305 58 L355 15" fill="none" stroke="#b6ff00" strokeWidth="3" pathLength="1"/><circle cx="355" cy="15" r="5" fill="#b6ff00"/></svg><div className="hero-report-foot"><span>ANALISAR</span><span>OTIMIZAR</span><span>CRESCER</span></div><p>Dados ilustrativos</p></div><div className="hero-foot"><span>RISE AGENCY / TRÁFEGO PAGO COM DIREÇÃO</span><span>EXPLORE O PRÓXIMO CAPÍTULO ↓</span></div></section>
<div className="ribbon" aria-hidden="true"><span>CLÍNICAS</span><i>✳</i><span>RESTAURANTES</span><i>✳</i><span>ESCOLAS</span><i>✳</i><span>E-COMMERCE</span><i>✳</i><span>E O SEU NEGÓCIO</span></div>
<section className="manifesto section"><span className="eyebrow">01 / TRÁFEGO PAGO COM DIREÇÃO</span><h2><span className="muted">Cliques são o começo.</span><br/><strong>Seu negócio precisa<br/>do que vem depois.</strong></h2><p>Campanhas, criativos e conversão conectados ao que importa:<br className="desktop"/> oportunidades, pedidos e vendas.</p></section><TrafficScene/>
<TemakExperience/>
<section className="section results" id="resultados"><div className="section-heading reveal"><div><span className="eyebrow">03 / RESULTADOS NA PRÁTICA</span><h2>O trabalho aparece.<br/><span>Os números também.</span></h2></div><p>Cada negócio tem um contexto.<br/>Estes são alguns dos nossos.</p></div><div className="metrics"><article><span className="metric-tag">DELIVERY</span><ScrollMetric target={500000} prefix="+ R$" label="Mais de 500 mil reais em vendas de delivery"/><p>Em vendas de delivery</p><a href="#case-results" onClick={()=>setSelected(0)}>Conheça o contexto</a></article><article><span className="metric-tag">ORQUÍDEAS · E-COMMERCE</span><ScrollMetric target={1000000} prefix="+ R$" label="Mais de 1 milhão de reais em vendas de orquídeas pelo site"/><p>Em vendas de orquídeas pelo site</p><a href="#case-results" onClick={()=>setSelected(1)}>Conheça o contexto</a></article><article><span className="metric-tag">DIFERENTES NEGÓCIOS</span><ScrollMetric target={50000} prefix="+" label="Mais de 50 mil leads gerados"/><p>Leads gerados para diferentes negócios</p><a href="#case-results" onClick={()=>setSelected(2)}>Conheça o contexto</a></article></div><p className="fine">Volumes acumulados informados pela Rise. Cada negócio tem seu contexto; resultados anteriores não garantem desempenho futuro.</p></section>
<section className="section ecosystem" id="servicos"><div className="ecosystem-intro"><span className="eyebrow">04 / GESTÃO QUE CONECTA AS PONTAS.</span><h2>Tráfego pago.<br/>Com todas as<br/><em>pontas ligadas.</em></h2><p>Planejamos, executamos e acompanhamos suas campanhas. O anúncio é parte de uma operação que precisa funcionar até a venda.</p><a className="text-link" href={whatsappUrl} target="_blank" rel="noopener noreferrer">Vamos olhar para o seu negócio</a><div className="ecosystem-brand" aria-hidden="true"><img src="/rise-logo-transparent.png" alt=""/></div></div><div className="service-list">{services.map(s=><article className="service reveal" key={s.n}><span>{s.n}</span><div><h3>{s.title}</h3><p>{s.desc}</p><small>{s.items}</small></div></article>)}</div></section>

<section className="section cases" id="case-results"><div className="section-heading reveal"><div><span className="eyebrow">05 / POR TRÁS DO NÚMERO</span><h2>Contexto transforma<br/>número em evidência.</h2></div></div><div className="case-selector" aria-label="Selecionar case">{cases.map((item,i)=><button key={item.tag} aria-pressed={selected===i} onClick={()=>setSelected(i)}>{item.tag}</button>)}</div><article className="case-panel" aria-live="polite"><div className="case-visual"><span className="eyebrow">RISE / {c.tag}</span><div className="case-number">{c.value}</div><span>{c.unit}</span><div className="case-lines" aria-hidden="true">{[22,31,28,44,41,57,53,70,66,84,78,100].map((v,i)=><div key={i} style={{height:v+'%'}}/>)}</div><small>GRAFISMO CONCEITUAL · NÃO É UMA SÉRIE HISTÓRICA</small></div><div className="case-copy"><span className="eyebrow">CASE {String(selected+1).padStart(2,'0')}</span><h3>{c.title}</h3><p>{c.desc}</p><div className="case-stats">{c.stats.map(s=><div key={s[1]}><strong>{s[0]}</strong><span>{s[1]}</span></div>)}</div><p className="fine">{c.note}</p><a className="text-link" href={whatsappUrl} target="_blank" rel="noopener noreferrer">Quero conversar sobre minha empresa</a></div></article><p className="fine">Os materiais visuais dos clientes e os períodos completos de cada case serão incorporados após validação.</p></section>
<section className="section method" id="metodo"><div className="section-heading reveal"><div><span className="eyebrow">06 / PROXIMIDADE É PARTE DO MÉTODO</span><h2>Clareza em cada etapa.<br/>E gente por perto.</h2></div><p>Você acompanha as decisões.<br/>Nós conectamos estratégia e execução.</p></div><div className="steps">{[['Escutar','Entender seu negócio, seus objetivos e o ponto de partida.'],['Planejar','Definir prioridades, canais e o que será acompanhado.'],['Executar','Colocar anúncios, criativos e páginas de conversão para trabalhar.'],['Evoluir','Analisar campanhas, acompanhar conversões e ajustar o investimento.']].map(([a,b],i)=><article className="reveal" key={a}><span>0{i+1}</span><h3>{a}</h3><p>{b}</p></article>)}</div></section>
<section className="belief section reveal"><span className="eyebrow">CRESCIMENTO É UM TRABALHO EM CONJUNTO.</span><h2>Sem fórmula mágica.<br/>Com direção, investimento<br/>e <em>consistência.</em></h2><p>A Rise é para empresas que querem construir o próximo capítulo com uma equipe próxima, estratégia clara e execução contínua.</p></section>
<section className="section contact contact-direct" id="conversa"><div><span className="eyebrow">07 / O PRÓXIMO CAPÍTULO COMEÇA AQUI</span><h2>Vamos falar<br/>sobre o seu<br/><em>crescimento?</em></h2><p>Fale com a Rise pelo WhatsApp.<br/>Vamos conversar sobre o próximo passo do seu negócio.</p><a className="button" href={whatsappUrl} target="_blank" rel="noopener noreferrer">Vamos conversar no WhatsApp <span aria-hidden="true">↗</span></a><span className="contact-note">Tráfego pago + conversão + acompanhamento</span></div></section>
<footer><a className="logo brand-logo" href="#" aria-label="Rise Agency, início"><img src="/rise-logo-transparent.png" alt="Rise Agency"/></a><span>Tráfego pago. Crescimento com direção.</span><span>© {new Date().getFullYear()} Rise Agência</span><a href="#conteudo">Voltar ao início</a></footer></main>}
